### ISSUE TITLE
Link for Contribute a pull request! Broken in firefox and Chrome

### ISSUE THREAD

**Issue by sarehag** [mockito/mockito.github.io#11]
Link for Contribute broken on first page on mockito.org. User ends up at various places depending on browser.

I was going to create a pull request with a correction of the link, but could not find a page that actually contained contribution information. 

Should the link exist? If so, where should it point? My suggestion would be removing it if there is no information to link to.

**Comment by mockitoguy** [comment]
It has been fixed.
