### ISSUE TITLE
"Contributions welcome" items alignment

### ISSUE THREAD

**Issue by jeremy-techson** [mockito/mockito.github.io#25]
I don't know if it's the desired visual alignment for those items but it looks weird on my end. Please see image below. 

![mockito-alignment-issue](https://cloud.githubusercontent.com/assets/4848376/22458039/aa80d644-e7d5-11e6-9ca4-8115e9fa2018.PNG)

**Comment by bric3** [comment]
Hi @jemaystermind it seems related to the jekyll template. If you know how to fix this. We'll welcome your contribution.

**Comment by jeremy-techson** [comment]
I would love to. But I don't know how to fix it. Sorry.

**Comment by TimvdLippe** [comment]
Closed in #33
