### ISSUE TITLE
html: missing title in head

### ISSUE THREAD

**Issue by hastebrot** [mockito/mockito.github.io#3]
Hi,

http://mockito.org/ has no title tag.

**Update**: Webpage title is shown on Chrome (text: "mockito.org"), but missing in Firefox (both latests versions).

**Comment by bric3** [comment]
Thanks.

Indeed the top frame has no title. cc @szczepiq 

``` html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">
<HTML><HEAD><TITLE></TITLE></HEAD>
<FRAMESET ROWS="*"><FRAME NAME=997 NORESIZE SRC="http://mockito.github.io">
<NOFRAMES><BODY><A HREF="http://mockito.github.io">click here</A></BODY></NOFRAMES></FRAMESET></HTML>
```

By the way I see a `CNAME` file in the repository, it points to `site.mockito.org`. Maybe in the domain config we can simply redirect to `site.mockito.org` to get rid of that top level frame.

**Comment by mockitoguy** [comment]
This should be fixed now.
