### ISSUE TITLE
Dead link (to ReturnValues) on http://site.mockito.org/

### ISSUE THREAD

**Issue by DamianFekete** [mockito/mockito.github.io#41]
On [_posts/2000-01-15-more.md](https://github.com/mockito/mockito.github.io/blob/master/_posts/2000-01-15-more.md) the link to ReturnValues returns an error (as [ReturnValues](https://static.javadoc.io/org.mockito/mockito-core/1.9.5/org/mockito/ReturnValues.html) was deprecated).

Also the link to Answer points to http://javadoc.io/page/org.mockito/mockito-core/latest/org/mockito/Mockito.html#field_summary.
Shouldn't it be http://javadoc.io/page/org.mockito/mockito-core/latest/org/mockito/Mockito.html#answer_stubs or http://javadoc.io/page/org.mockito/mockito-core/latest/org/mockito/stubbing/Answer.html ?

Thanks for the site!

**Comment by TimvdLippe** [comment]
@DamianFekete Thanks for the note! Would you be so kind to also open a PR? I will happily merge the update 🎉

**Comment by DamianFekete** [comment]
@TimvdLippe, there are some other dead links.
Should for example `verify()` link to 
[https://static.javadoc.io/org.mockito/mockito-core/2.21.0/org/mockito/Mockito.html#verify-T-](https://static.javadoc.io/org.mockito/mockito-core/2.21.0/org/mockito/Mockito.html#verify-T-) or [https://static.javadoc.io/org.mockito/mockito-core/2.21.0/org/mockito/Mockito.html#verification](https://static.javadoc.io/org.mockito/mockito-core/2.21.0/org/mockito/Mockito.html#verification) ?
I would prefer links to examples (the second link).

**Comment by TimvdLippe** [comment]
The former please. Even though the latter gives more context, we are talking about the exact links to the methods. The readers are already invited to read the full documentation earlier on our website.
