### ISSUE TITLE
Out of date information

### ISSUE THREAD

**Issue by proski** [mockito/mockito.github.io#47]
Parts of the homepage still sound like the current version is 2 and version 3 has not been released.

"What's new in Mockito 2" should be "What's new in Mockito" and it should contain description of user visible changes in the latest versions, both 2.x and 3.x. Maybe it should be merged with the release notes mentioned on the next line.

"Still on Mockito 1.x?" is probably unnecessary. It's better not to single out specific versions, but to encourage users to update once in a while to benefit from recent development.

Linking to 3 sites hosting Mockito 1.x seems excessive. All those sites have information about the recent versions of Mockito as well. It would be better to describe what those sites provide (downloads, instructions, documentation) adjust the links to the latest version and let the users look for older versions if they want (most users would probably look for the latest version).

"After releasing Mockito 2 (see what’s new) the team will continue to improve version 2.x for a short time, then focus on Mockito 3." - completely out of date! I guess if can be removed.

"see what’s new" is not new, it's another link to "What's new in Mockito 2"

"Please provide your feedback and suggestions for the scope of Mockito 3.x" - it would be better not to frame it that way. Any constructive feedback should be welcome.

"Mockito 3.x will target Java 8." - I guess it should be Mockito 4.x or perhaps "the next major release".

**Comment by TimvdLippe** [comment]
Could you open a PR with the changes? Happy to merge improvements to the wording :smile:

**Comment by TimvdLippe** [comment]
> "Still on Mockito 1.x?" is probably unnecessary. It's better not to single out specific versions, but to encourage users to update once in a while to benefit from recent development.

Let's add some more guidance here. We do want to explicitly call out 1.x here, as we know a lot of our users are still on old versions. We would like to help them move to newer versions, which is why we explicitly call it out here.

> "Please provide your feedback and suggestions for the scope of Mockito 3.x" - it would be better not to frame it that way. Any constructive feedback should be welcome.

:+1: 

> "Mockito 3.x will target Java 8." - I guess it should be Mockito 4.x or perhaps "the next major release".

Note that Mockito 3 *does* target Java 8. So this is correct.
