### ISSUE TITLE
Updating Android Version

### ISSUE THREAD

**Issue by nikhil-seth** [mockito/mockito.github.io#52]
Currently, way to add  mockito as dependency on website is of form 

> dependencies { testCompile "org.mockito:mockito-core:2.+" }

In new versions, testCompile is deprecated. Better to replace it with testImplementation.
Also, the latest version is 3.+

**Comment by TimvdLippe** [comment]
@nikhil-seth Do you mind sending a PR to fix the docs? Thanks!

**Comment by nikhil-seth** [comment]
Sure @TimvdLippe
