### ISSUE TITLE
The style of javadoc pages seem to be broken

### ISSUE THREAD

**Issue by imba-tjd** [mockito/mockito.github.io#60]
https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html

![图片](https://github.com/mockito/mockito.github.io/assets/24759802/498042a0-acc6-417f-bbdb-f96f6ab84c87)

**Comment by scordio** [comment]
@TimvdLippe Shouldn't this issue be moved to `mockito/mockito` since it's not related to `mockito.github.io` / `mockito.org`?
